name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a one-line script
      - name: Run a one-line script
        run: echo Hello, world!

      # Copy .txt files, excluding RealHardware.txt
      - name: Copy txt files excluding RealHardware
        run: |
          mkdir -p ${{ github.workspace }}/output
          find . -name "*.txt" ! -name "*RealHardware.txt" -exec cp {} ${{ github.workspace }}/output/ \;

      # Upload the copied files as an artifact
      - name: Upload output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: copied-txts
          path: ${{ github.workspace }}/output

