name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Run a script to list files excluding RealHardware.txt
      - name: List STS files excluding RealHardware.txt
        run: |
          echo "Listing STS*.txt files but excluding RealHardware.txt:"
          find . -name "STS*.txt" ! -name "*.RealHardware.txt"

      # If you need to process those files, you can use a loop here
      # For example:
      - name: Process valid files
        run: |
          for file in $(find . -name "STS*.txt" ! -name "*.RealHardware.txt"); do
            echo "Processing $file"
            # Add additional steps to process the files if needed
          done
